[package]
name = "check-in-note"
version = "0.1.0"

[lib]
path = "src/lib.rs"
kind = "note"
namespace = "miden:check-in-note/miden-check-in-note@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"
heirbeat-vault = { path = "../heirbeat-vault" }

[package.metadata.miden.dependencies]
heirbeat-vault = { path = "../heirbeat-vault" }
