[package]
name = "touch-note"
version = "0.1.0"

[lib]
kind = "note"
namespace = "miden:touch-note/touch@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"
probe-account = { path = "../probe-account" }

[package.metadata.miden.dependencies]
probe-account = { wit = "../probe-account/target/generated-wit/" }
