[package]
name = "heirbeat-vault"
version = "0.1.0"

[lib]
kind = "account-component"
namespace = "miden:heirbeat-vault/heirbeat-vault@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"

[package.metadata.miden]
supported-types = ["RegularAccountImmutableCode"]
